### ISSUE TITLE
Events tab shows empty when querying extrinsic in long form ID

### ISSUE THREAD

**Issue by ken-futureverse** [rootscan/rootscan-io#37]
Doesn't work: https://porcini.rootscan.io/extrinsics/0011448183-000001-c37a6/events

Works: https://porcini.rootscan.io/extrinsics/11448183-1/events

<img width="1386" alt="Screenshot 2024-03-12 at 13 40 48" src="https://github.com/rootscan/rootscan-io/assets/97480229/0c717886-01ec-40c0-adc8-f04e72b0d1b6">

**Comment by yariksav** [comment]
closed by https://github.com/rootscan/rootscan-io/pull/42
