### ISSUE TITLE
Events view should be sorted by its ID, rather by block

### ISSUE THREAD

**Issue by ken-futureverse** [rootscan/rootscan-io#38]
<img width="1354" alt="Screenshot 2024-03-12 at 13 44 20" src="https://github.com/rootscan/rootscan-io/assets/97480229/d7f3f58f-04a0-47ec-9421-9ea3b426e8e4">

**Comment by olexiyb** [comment]
Added direct link to [example](https://porcini.rootscan.io/extrinsics/11448183-1/events)

**Comment by yariksav** [comment]
closed by https://github.com/rootscan/rootscan-io/pull/42
