### ISSUE TITLE
Failed Utility Batch Extrinsic shown as Successful

### ISSUE THREAD

**Issue by RichieRichCR** [rootscan/rootscan-io#57]
Hi Team,

I was doing some tests with utility batch extrinsics and deliberately included an extrinsic that would cause the batch to fail - you can see here (https://porcini.rootscan.io/extrinsics/12367803-1) that it seems like the extrinsic was successful and the tokens were transferred, but comparing to old explorer (https://explorer.rootnet.cloud/extrinsic/0012367803-000001-527f4) you can see the batch failed and no tokens were transferred...

**Comment by pbendus** [comment]
Hey @RichieRichCR

Would you mind joining our [Discord Server](https://discord.gg/2Sb9ZWRgBn) to discuss some details on this one?
